### ISSUE TITLE
Conflict with Whitelist script

### ISSUE THREAD

**Issue by YisusOnDev** [pilate/WorkingMan#1]
If i use WorkingMan whitelist stop working properly and allow any user to join.

**Comment by mothball187** [comment]
@YisusOnDev I think I know why this happens. Can you link me to the plugin you are using for whitelisting on your server? Thanks!

**Comment by mothball187** [comment]
@YisusOnDev I no longer have a Rust server to test plugin updates on, but if you would like you can try https://github.com/pilate/WorkingMan/blob/new-login-check/WorkingMan.cs from the new-login-check branch to see if that fixes your issue. Please let me know if it works and I can update github and uMod with the new version, thanks!

**Comment by NoFiixx** [comment]
Having the same issue, the plugin im using is Whitelist by Wulf: https://umod.org/plugins/whitelist

**Comment by jtbennett-fe** [comment]
@NoFiixx can you please try the new version of the plugin on the new-login-check branch? If you are not familiar with using git, you can simply browse to https://raw.githubusercontent.com/pilate/WorkingMan/279892d4aec5a78e9fa55a0ad79bb9e8c7b0a708/WorkingMan.cs and copy all this code into a text file named WorkingMan.cs and deploy that version onto your server.

**Comment by NoFiixx** [comment]
> @NoFiixx can you please try the new version of the plugin on the new-login-check branch? If you are not familiar with using git, you can simply browse to https://raw.githubusercontent.com/pilate/WorkingMan/279892d4aec5a78e9fa55a0ad79bb9e8c7b0a708/WorkingMan.cs and copy all this code into a text file named WorkingMan.cs and deploy that version onto your server.


Thank u, This solved the problem, Thank u so much :·)
